spring:
  application:
    name: eureka-ha
---
spring:
  profiles: peer1 
                       
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 3                               
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/      

---
spring:
  profiles: peer2

server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 3
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
