# create aim db tables

USE AIMDB;

CREATE TABLE CONTAINERS (
    CONTAINER_ID          INT(8)  NOT NULL,
    CONTAINER_NAME        VARCHAR(20)  NOT NULL ,
    SCOPE_ID              INT(8)  NOT NULL ,
    FORMAT_ID             INT(8)  NOT NULL ,
    MIN_REDUNDANCY        INT(8)  NULL ,
    MIN_MU_NUM_FOR_SLB    INT(8)  NULL ,
    MAX_SEGMENT_SIZE      BIGINT(38)  NOT NULL ,
    PRIMARY KEY(CONTAINER_ID ),
   UNIQUE CONTAINERS_PK (CONTAINER_ID) 
) TABLESPACE AIM_MAIN_DATA ENGINE=INNODB;


CREATE TABLE CONTAINER_JOB_FAILURE_REASONS (
    FAILURE_ID           BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CODE                 VARCHAR(20) NOT NULL ,
    REASON               VARCHAR(4000)  NOT NULL ,
    FAILURE_TIME         VARCHAR(128) NOT NULL ,
    MR_ID                INT(8)  NULL ,
    CONTAINER_JOB_ID     BIGINT(38)  NOT NULL ,
    SEGMENT_ID           BIGINT(28)  NULL ,
    UNIQUE C_JOB_FAILURE_REASONS_PK (FAILURE_ID ASC)
) TABLESPACE AIM_SEARCH_JOB_DATA ENGINE=INNODB;


CREATE TABLE CONTAINER_JOBS (
    CONTAINER_JOB_ID        BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTAINER_ID            INT(8)  NOT NULL ,
    FUSION_JOB_ID           BIGINT(38)  NOT NULL ,
    MR_ID                   INT(8)  NULL ,
    CONTAINER_JOB_RESULT    MEDIUMBLOB  NULL ,
    RESULT_TS               BIGINT(38)  NULL ,
    ASSIGNED_TS             BIGINT(38)  NULL ,
    JOB_STATE               INT(4)  DEFAULT 0 NOT NULL,
    PLAN_ID                 BIGINT(38)  NULL ,
    UNIQUE CONTAINER_JOBS_PK (CONTAINER_JOB_ID ASC)
) TABLESPACE AIM_SEARCH_JOB_DATA ENGINE=INNODB;


CREATE TABLE DM_SERVICES (
    DM_ID                 INT(8)  NOT NULL PRIMARY KEY,  
    CONTACT_URL           VARCHAR(256)  NULL ,
    HEATBEAT_PORT         INT(5), 
    STATE                 VARCHAR(16)  NOT NULL ,
    VERSION               VARCHAR(32) ,   
    UNIQUE DATA_MANAGERS_PK (DM_ID ASC)
) TABLESPACE AIM_MAIN_DATA ENGINE=INNODB;


CREATE TABLE EXTRACT_COMPLETE_COUNT
(
    COMPLETE_COUNT      BIGINT(38)  NOT NULL ,
    COMPLETE_TS         BIGINT(38)  NOT NULL
) TABLESPACE AIM_MAIN_DATA ENGINE=INNODB;


CREATE TABLE FE_JOB_FAILURE_REASONS (
    FAILURE_ID            BIGINT(38)  NOT NULL AUTO_INCREMENT AUTO_INCREMENT PRIMARY KEY,
    JOB_ID                BIGINT(38)  NOT NULL ,
    MU_ID                 INT(8)   NOT NULL ,
    CODE                  VARCHAR(20) NOT NULL ,
    REASON                VARCHAR(4000)  NOT NULL ,
    FAILURE_TIME          VARCHAR(128) NOT NULL ,
    UNIQUE FE_JOB_FAIL_REASONS_PK (FAILURE_ID ASC)
) TABLESPACE AIM_EXTRACT_JOB_DATA  ENGINE=INNODB;


CREATE TABLE FE_JOB_PAYLOADS (
    PAYLOAD_ID            BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PAYLOAD               MEDIUMTEXT  NULL ,
    JOB_ID                BIGINT(38)  NOT NULL ,
    UNIQUE  FE_JOB_PAYLOADS_PK (PAYLOAD_ID ASC)   
) TABLESPACE AIM_EXTRACT_JOB_DATA  ENGINE=INNODB;


CREATE TABLE FE_JOB_QUEUE (
    JOB_ID                 BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOT_JOB_ID             BIGINT(38)  NULL ,
    UIDAI_REQUEST_ID       VARCHAR(36) UNIQUE NOT NULL, 
    FUNCTION_ID            INT(4)  NOT NULL , 
    REFERENCE_ID           VARCHAR(36) UNIQUE ,
    PRIORITY               INT(4)  DEFAULT 5 NOT NULL ,
    JOB_STATE              INT(4)  NOT NULL ,
    FAILED_FLAG            INT(4)  NULL ,
    MU_ID                  INT(8)  NULL ,
    ASSIGNED_TS            BIGINT(38)  NULL ,
    RESULT_TS              BIGINT(38)  NULL ,
    RESULT                 MEDIUMTEXT  NULL , 
    DIAGNOSTICS            MEDIUMBLOB  NULL ,
    SUBMISSION_TS          BIGINT(38)  NOT NULL ,
    FAILURE_COUNT          INT(4)   DEFAULT  0 NULL ,
    CALLBACK_URL           VARCHAR(4000) NULL ,  
    CALLBACK_STYLE         INT(2)  NULL ,  
    INDEX FE_JOB_QUEUE_PK  (JOB_ID ASC)
) TABLESPACE AIM_EXTRACT_JOB_DATA  ENGINE=INNODB;


CREATE TABLE FE_LOT_JOBS (
    LOT_JOB_ID            BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MU_ID                 INT(8)   NOT NULL ,
    ASSIGNED_TS           BIGINT(38)  NOT NULL ,
    TIMEOUTS              INT(16)  NOT NULL ,
    UNIQUE  FE_LOT_JOBS_PK (LOT_JOB_ID ASC) 
) TABLESPACE AIM_EXTRACT_JOB_DATA  ENGINE=INNODB;


CREATE TABLE FORMAT_TYPES (
    FORMAT_ID             INT(4)  NOT NULL PRIMARY KEY ,
    DETAILS               VARCHAR(128)  NULL ,
    FORMAT_NAME           VARCHAR(32)  NOT NULL , 
    UNIQUE FORMAT_TYPES_PK (FORMAT_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE INQUIRY_TRAFFIC (
    FAMILY_ID           INT(4)  NOT NULL PRIMARY KEY,
    FAMILY_NAME         VARCHAR(32)  NOT NULL ,
    JOB_LIMIT_COUNT     INT(8) ,  
    JOB_EXEC_COUNT      INT(8) ,
    JOB_COMPLETE_COUNT  BIGINT(38) ,
    UNIQUE INQUIRY_TRAFFIC_PK (FAMILY_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE FUNCTION_TYPES (
    FUNCTION_ID                 INT(4)  NOT NULL PRIMARY KEY,
    FUNCTION_NAME               VARCHAR(32)  NOT NULL ,
    TARGET_FORMAT_ID            INT(4)  NULL ,
    QUEUE_TYPE                  INT(4)  NOT NULL ,
    FAMILY_ID                   INT(4)  NULL ,
    TOP_LEVEL_JOB_TIMEOUTS      INT(16)  DEFAULT -1 NOT NULL ,
    CONTAINER_JOB_TIMEOUTS      INT(16)  DEFAULT -1 NOT NULL ,
    INTERNAL_CANDIDATE_SIZE     INT(6)  NULL ,
    UNIQUE FUNCTION_TYPES_PK (FUNCTION_ID ASC) 
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE FUSION_JOBS (
    FUSION_JOB_ID         BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FUNCTION_ID           INT(4)  NOT NULL ,
    JOB_ID                BIGINT(38)  NOT NULL ,
    INQUIRY_JOB_XML       MEDIUMTEXT  NULL ,
    INQUIRY_PROBE_DATA    MEDIUMBLOB  NULL ,
    SEARCH_REQUEST_INDEX  INT(2)  NOT NULL ,
	UNIQUE FUSION_JOBS_PK  (FUSION_JOB_ID ASC)
    ) TABLESPACE AIM_SEARCH_JOB_DATA  ENGINE=INNODB;


CREATE TABLE JOB_QUEUE (
    JOB_ID                      BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    UIDAI_REQUEST_ID            VARCHAR(36) UNIQUE NOT NULL, 
    PRIORITY                    INT(4)  DEFAULT 5  NULL ,
    JOB_STATE                   INT(4)  DEFAULT 0 NOT NULL ,
    RESULT                      MEDIUMTEXT  NULL , 
    DIAGNOSTICS                 MEDIUMBLOB  NULL ,  
    RESULT_TS                   BIGINT(38)  NULL ,
    SUBMISSION_TS               BIGINT(38)  NOT NULL ,
    ASSIGNED_TS                 BIGINT(38)  NULL ,
    FAILED_FLAG                 INT(2)  NULL ,
    CALLBACK_URL                VARCHAR(2000)  NULL , 
    CALLBACK_STYLE              INT(2)  NULL ,
    MAX_CANDIDATES              INT(8)  NULL , 
    DYNTHRESH_PERCENTAGE_POINT  INT  NULL ,
    DYNTHRESH_HIT_THRESHOLD     INT(8)  NULL , 
    TIMEOUTS                    INT(16)  DEFAULT -1 NOT NULL ,
    FAILURE_COUNT               INT(4)  DEFAULT 0 NOT NULL ,
    REMAIN_JOBS                 INT(8)  DEFAULT 0 NOT NULL ,
    FAMILY_ID                   INT(4)  NOT NULL ,
    UNIQUE JOB_QUEUE_PK (JOB_ID ASC) 
) TABLESPACE AIM_SEARCH_JOB_DATA  ENGINE=INNODB;


CREATE TABLE LAST_ASSIGNED_MR (
    ASSIGNED_LOCATION     INT(8)  NOT NULL ,
    ASSIGNED_TS           BIGINT(38)  NOT NULL
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MATCH_MANAGERS (
    MM_ID                 INT(8)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UNIQUE_ID             VARCHAR(32)  NOT NULL ,
    STATE                 VARCHAR(16)  NOT NULL ,
    CONTACT_URL           VARCHAR(64)  NULL ,
    HEARTBEAT_TS          BIGINT(38)  NULL ,
    VERSION               VARCHAR(32) ,
    UNIQUE  MATCH_MANAGERS_PK (MM_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MATCH_UNITS (
    MU_ID                 INT(8)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UNIQUE_ID             VARCHAR(32)  NOT NULL ,
    CONTACT_URL           VARCHAR(64)  NULL ,
    STATE                 VARCHAR(16)  NOT NULL ,
    PRIMARY_SIZE          BIGINT(32)  NULL ,
    SECONDARY_SIZE        BIGINT(32)  NULL ,
    REPORTED_PERFORMANCE_FACTOR  FLOAT(126,0)  NULL ,
    NUMBER_OF_MATCHERS    INT(8)  NULL ,
    NUMBER_OF_EXTRACTORS  INT(8)  NULL ,
    VERSION               VARCHAR(32) ,
    UNIQUE MATCH_UNITS_PK  (MU_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MAP_REDUCERS (
    MR_ID                 INT(8)  NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    RING_LOCATION         INT(8)  NULL ,
    UNIQUE_ID             VARCHAR(32)  NOT NULL ,
    CONTACT_URL           VARCHAR(64)  NULL ,
    STATE                 VARCHAR(16)  NOT NULL ,
    VERSION               VARCHAR(32) ,
    INDEX MAP_REDUCERS_PK (MR_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MM_EVENTS (
    NAME                  VARCHAR(64)  NOT NULL PRIMARY KEY ,
    LAST_TS               BIGINT(38) NOT NULL ,
    MM_ID                 INT(8)  NOT NULL , 
    UNIQUE MM_RESERVED_FUNCTIONS_PK  (NAME ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MR_CONTACTS (
    MR_ID                 INT(8)  NOT NULL PRIMARY KEY,
    CONTACT_TS            BIGINT(38)  NOT NULL ,
    UNIQUE MR_CONTACTS_PK (MR_ID ASC) 
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MU_CONTACTS (
    MU_ID                 INT(8)  NOT NULL  PRIMARY KEY,
    CONTACT_TS            BIGINT(38)  NOT NULL ,
    UNIQUE INDEX MU_CONTACTS_PK  (MU_ID ASC) 
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MU_ELIGIBLE_CONTAINERS (
    MU_ID                 INT(8)  NOT NULL ,
    CONTAINER_ID          INT(8)  NOT NULL ,
    PRIMARY KEY (MU_ID,CONTAINER_ID),
    UNIQUE MU_ELIGIBLE_CONTAINERS_PK (MU_ID ASC, CONTAINER_ID ASC) 
)  TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MU_ELIGIBLE_FUNCTIONS (
    MU_ID                 INT(8)  NOT NULL ,
    FUNCTION_ID           INT(4)  NOT NULL ,
    PRIMARY KEY (FUNCTION_ID,MU_ID) ,
    UNIQUE MU_ELIGIBLE_FUNCTIONS_PK (FUNCTION_ID ASC, MU_ID ASC)    
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MU_JOB_EXECUTE_PLANS (
    PLAN_ID               BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    JOB_ID                BIGINT(38)  NOT NULL ,
    FUNCTION_ID           INT(4)  NOT NULL ,
    CONTAINER_ID          INT(8)  NOT NULL ,
    PLAN                  MEDIUMTEXT NOT NULL ,
    PLANED_COUNT          INT(4)  NOT NULL ,
    PLANED_TS             BIGINT(38)  NOT NULL ,
    UNIQUE INDEX MU_JOB_EXECUTE_PLANS_PK (PLAN_ID ASC) 
) TABLESPACE AIM_SEARCH_JOB_DATA  ENGINE=INNODB;

CREATE TABLE MU_EXTRACT_LOAD (
    MU_ID       INT(8)  NOT NULL  PRIMARY KEY ,
    PRESSURE    INT(8)  NOT NULL ,
    UPDATE_TS   BIGINT(38)  NOT NULL ,
    UNIQUE MU_EXTRACT_LOAD_PK (MU_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MU_INQUIRY_LOAD (
    MU_ID               INT(8)  NOT NULL PRIMARY KEY,
    PRESSURE            BIGINT(38)  NULL ,
    REPORT_TS           BIGINT(38) ,
    UNIQUE MU_INQUIRY_LOAD_PK (MU_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MU_SEG_REPORTS (
    MU_ID                   INT(8)  NOT NULL ,
    SEGMENT_ID              BIGINT(28)  NOT NULL ,
    STATUS                  INT(4)  NOT NULL ,
    SEGMENT_VERSION         BIGINT(38)  NULL ,
    SEGMENT_QUEUED_VERSION  BIGINT(38)  NULL ,
     PRIMARY KEY (MU_ID,SEGMENT_ID),
     UNIQUE MU_SEG_REPORTS_PK (MU_ID ASC, SEGMENT_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE MU_SEGMENTS (
    MU_ID                 INT(8)  NOT NULL ,
    SEGMENT_ID            BIGINT(28)  NOT NULL ,
    AIM_RANK                 INT(4)  NOT NULL ,
    PRIMARY KEY (MU_ID,SEGMENT_ID) ,
    UNIQUE MU_SEGMENTS_PK (MU_ID ASC, SEGMENT_ID ASC) 
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE RESOURCE_UPDATE_COUNT (
    UPDATE_COUNT        BIGINT(38)  NOT NULL ,
    UPDATE_TS           BIGINT(38)  NOT NULL
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;;


CREATE TABLE PERSON_BIOMETRICS (
    BIOMETRICS_ID         BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    EXTERNAL_ID           VARCHAR(36)  NOT NULL UNIQUE,
    REGISTED_TS           BIGINT(38) NOT NULL ,
    CORRUPTED_FLAG        INT(4)  DEFAULT  0 NOT NULL ,   
    CONTAINER_ID          INT(8)  NOT NULL , 
    UNIQUE PERSON_BIOMETRICS_PK (BIOMETRICS_ID ASC)
) TABLESPACE AIM_BIOMETRICS_DATA  ENGINE=INNODB;


CREATE TABLE SCOPES (
    SCOPE_ID         INT(8)  NOT NULL PRIMARY KEY,
    UNIQUE SCOPES_PK (SCOPE_ID ASC)

) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS SEGMENT_CHANGE_LOG (
  SEGMENT_CHANGE_ID BIGINT(38) ,
  BIOMETRICS_ID BIGINT(38)  NOT NULL,
  EXTERNAL_ID VARCHAR(36),
  TEMPLATE_DATA BLOB  NULL,   
  SEGMENT_ID BIGINT(38)  NOT NULL ,
  SEGMENT_VERSION BIGINT(38)  NOT NULL ,
  CHANGE_TYPE INT(4)  NOT NULL,   #new:0,insert:1,delete:2,update:3 
  UPDATE_TS DATE  NOT NULL,
  P_NO BIGINT NOT NULL,
  PRIMARY KEY (SEGMENT_CHANGE_ID,P_NO)
)  ENGINE=INNODB;


CREATE TABLE SEGMENTS (
    SEGMENT_ID                  BIGINT(38)  NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    CONTAINER_ID                INT(8)  NOT NULL ,
    BIO_ID_START                BIGINT(38)  NOT NULL ,
    BIO_ID_END                  BIGINT(38)  NOT NULL ,   
    VERSION                     BIGINT(38)  NOT NULL ,
    REVISION                    BIGINT(38)  NOT NULL ,   
    UNIQUE SEGMENTS_PK (SEGMENT_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE SEGMENT_VACANCIES (
        VACANCIES_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SEGMENT_ID BIGINT(38) NOT NULL ,  
	BIOMETRICS_ID BIGINT(38) NOT NULL , 
	VACANCY_TS BIGINT UNSIGNED NOT NULL,
        FOREIGN KEY (SEGMENT_ID) REFERENCES SEGMENTS(SEGMENT_ID),
        FOREIGN KEY (BIOMETRICS_ID) REFERENCES PERSON_BIOMETRICS(BIOMETRICS_ID)
) TABLESPACE AIM_BIOMETRICS_DATA  ENGINE=INNODB;


CREATE TABLE SYSTEM_CONFIG (
    CONFIG_ID             INT(8)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PROPERTY_NAME         VARCHAR(64)  NOT NULL ,
    PROPERTY_VALUE        VARCHAR(256)  NOT NULL ,
    UNIQUE SYSTEM_CONFIG_PK (CONFIG_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE SYSTEM_INIT (
    INIT_ID               INT(8)  NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    KEY_NAME              VARCHAR(64)  UNIQUE NOT NULL ,
    KEY_VALUE             VARCHAR(256)  NOT NULL ,
    UNIQUE SYSTEM_INIT_PK  (INIT_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;


CREATE TABLE SYSTEM_MANAGERS (
    SM_ID                 INT(8)  NOT NULL PRIMARY KEY,
    UNIQUE_ID             VARCHAR(32)  NOT NULL ,
    CONTACT_URL           VARCHAR(64)  NULL ,
    STATE                 VARCHAR(16)  NOT NULL ,
    VERSION               VARCHAR(38) ,
    UNIQUE SYSTEM_MANAGERS_PK (SM_ID ASC)
) TABLESPACE AIM_MAIN_DATA  ENGINE=INNODB;