version: "3"

services:

  cassandra-1:
    container_name: cassandra-1
    networks: ["vnet"]
    hostname: cassandra-1.vnet
    image: smizy/cassandra:3.11-alpine
    ports:
      - 9042:9042
      - 9160:9160
      - 7199:7199
      - 8778:8778
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1.vnet,cassandra-2.vnet,cassandra-3.vnet
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=200M

  cassandra-2:
    container_name: cassandra-2
    networks: ["vnet"]
    hostname: cassandra-2.vnet
    image: smizy/cassandra:3.11-alpine
    ports:
      - 9142:9042
      - 9260:9160
      - 7299:7199
      - 8878:8778
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1.vnet,cassandra-2.vnet,cassandra-3.vnet
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=200M

  cassandra-3:
    container_name: cassandra-3
    networks: ["vnet"]
    hostname: cassandra-3.vnet
    image: smizy/cassandra:3.11-alpine
    ports:
      - 9242:9042
      - 9360:9160
      - 7399:7199
      - 8978:8778
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1.vnet,cassandra-2.vnet,cassandra-3.vnet
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=200M
      
  megha:
    container_name: megha
    networks:
       - vnet
    hostname: megha
    image: megha
    links:
      - cassandra-1
      - cassandra-2
      - cassandra-3
    ports:
      - '8080:8080'
      - '9990:9990'

networks:
  vnet:
    external:
      name: vnet 
