server:
  port: 8761

spring:
  application:
     name: eurka-server
  security:  
     user:
       name: aimxmuser
       password: 12345678

eureka:
  instance:
    hostname: localhost    
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
       defaultZone: http://aimxmuser:12345678@${eureka.instance.hostname}:${server.port}/eureka/ 
       