server:
  port: 8000
spring:
  application:    
    name: template-service
  jpa:    
    show-sql: true
logging:
  level:
    root: INFO   
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
management:
  endpoints:
    web:
      exposure:        
        include: '*'
  endpoint:
    health:      
      show-details: always

eureka:
  client:
    service-url:      
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:    
    prefer-ip-address: true

